### PR TITLE
issue #43: fix the activities order

### PR DESCRIPTION
**Pull request by HamidRezaSZ**
I updated the SQL command in _get_activities_by_user_id() function to return activities order by added_at field in ascending order.

### CODE REVIEW

**Comment by dmossakowski** [comment]
Thank you Hamid but if I could please ask that instead of forking the project you do the following:
- clone the repository from this project: git@github.com:dmossakowski/skala3ma.git
- create new branch: git checkout -b hamid/my_new_fix
- make modifications as you want, commit and push your branch
- create the PR for review

This will make it easier for me to review changes because I can quickly checkout your branch. Forking a project should really only be done if you plan on diverging from the main project to do your own thing.

**Comment by HamidRezaSZ** [comment]
I think I don't have permission to create a branch.

**Comment by dmossakowski** [comment]
I added you as a collaborator so you should have access now

**Comment by HamidRezaSZ** [comment]
Thank you

**Pull request closed without merging**
